# Generated by Django 4.0.3 on 2022-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_detail_date_alter_detail_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='date',
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterModelTable(
            name='detail',
            table='myapp_image',
        ),
    ]
