# Generated by Django 4.0.3 on 2022-03-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_detail_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail',
            table=None,
        ),
    ]
