# Generated by Django 4.0.3 on 2022-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_detail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='image',
        ),
    ]
