# Generated by Django 4.0.3 on 2022-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
