# Generated by Django 4.0.3 on 2022-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_detail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
